### PR TITLE
Optimized Cucumber output

### PR DESCRIPTION
**Pull request by kevgo**
@alexdavid @dhakiki 

* uses the "dot"-formatter when running all feature specs (nobody wants to read all that output)
* provides a "cute" command that runs an individual feature spec using the "pretty" formatter 

What do you think?

### CODE REVIEW

**Comment by alexdavid** [comment]
LGTM

I feel like we're using this cuke script in a bunch of projects (and it's super helpful). Maybe we can publish it as an npm package?

**Comment by kevgo** [comment]
Yeah, if we use it in more than a few places, I'll make an NPM package out of it.

**Comment by kevgo** [comment]
@alexdavid correction on this PR, please re-review!

I was able to pinpoint the reason why we can't just run `cucumber-js` here. The file `features/step_definitions/run_steps.coffee` exported a function, and Cucumber.JS somehow handles that case differently. Changing the export to a hash allows us to now run `cucumber-js [filename]` directly, thereby removing the need for the `cuke` helper.

**Comment by alexdavid** [comment]
Awesome, thanks for fixing this Kevin!

**Pull request closed without merging**
